# Generated by Django 5.0.1 on 2024-02-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=2083, null=True)),
                ('address', models.CharField(max_length=2083, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_click_date', models.DateTimeField(null=True)),
                ('click_times', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
