# Generated by Django 5.0.1 on 2024-02-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='category1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.indexcategory'),
        ),
    ]
