# Generated by Django 5.0.1 on 2024-02-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_index_category1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=2083, null=True)),
                ('task_due_date', models.DateTimeField(blank=True, null=True)),
                ('task_done', models.BooleanField(default=False)),
                ('task_created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
