# Generated by Django 5.0.1 on 2024-02-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_todotask'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcategory',
            name='category_order_num',
            field=models.IntegerField(default=99, null=True),
        ),
    ]
