# Generated by Django 5.0.1 on 2024-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_indexcategory_category_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='task_reminder1_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='task_reminder2_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
